version: '3.9'

services:

  mysql:
    image: mysql:8.0.32
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: cc9944aaff
      MYSQL_DATABASE: demo
    volumes:
      - ./src/Database:/docker-entrypoint-initdb.d
